on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/setup-pages@v1
      - name: Upload artifact
        run: |
          mkdir -p public
          cp -r 所有程式/* public/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public